name: Acc Tests
on:
  push:
    branches:
      - master
      - "release/**"
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '**.go'
      - go.mod
      - '.github/workflows/**'

env:
  GOPROXY: https://proxy.golang.org,https://gocenter.io,direct
  DEBIAN_FRONTEND: noninteractive
  DOCKER_CE_VERSION: "5:20.10.5~3-0~ubuntu-focal"
  GO_VERSION: "1.16"

jobs:
  acc-test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        terraform_version: 
        - "0.12.31"
        - "0.13.7"
        - "0.14.11"
        - "0.15.2"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: cat /etc/issue
      - run: bash scripts/gogetcookie.sh
      # locally: docker run -it ubuntu:20.04 bash (https://ubuntu.pkgs.org/20.04/docker-ce-stable-amd64/)
      - run: sudo apt-get update
      - run: sudo apt-get -y install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - run: sudo apt-get update
      # list available docker versions: apt-cache policy docker-ce 
      - run: sudo apt-get -y install docker-ce=${DOCKER_CE_VERSION}
      - run: docker version
      - run: sudo service docker restart
      - run: make testacc
        env: 
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform_version }}
